[project]
title = "Marsh Coding Assessment"
version = "0.1.0"
port = 8501
slug = "structured-labs-526176"  
entrypoint = "hello.py"    

[branding]
name = "Marsh Coding Assessment"
logo = "apple.png"
favicon = "apple.ico"
primaryColor = "#F89613"

[data.student_habits_performance.csv]
type = "csv"
path = "data.student_habits_performance.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"